# Лёгкий базовый образ Node.js
FROM node:22-slim 

# Рабочая директория внутри контейнера
WORKDIR /app

# Прод-режим (влияет на npm и пакеты)
ENV NODE_ENV=production

# Копируем файлы зависимостей
COPY package*.json ./

# Устанавливаем только prod-зависимости
RUN npm ci --omit=dev

# Копируем код приложения
COPY app.js ./

# Документируем (открваем) порт
EXPOSE 3000

# Запуск приложения
CMD [ "node", "app.js" ]